#!/bin/bash

echo "export SECRET_KEY='$(openssl rand -hex 40)'" > ./.DJANGO_SECRET_KEY
source ./.DJANGO_SECRET_KEY


if [[ ! $(dpkg --get-selections | grep '^python3-pip.*install$') || ! $(dpkg --get-selections | grep '^virtualenv.*install$') || ! $(dpkg --get-selections | grep '^python-is-python3.*install$') ]]
then 
	apt install python-is-python3 python3-pip virtualenv -y
fi

if [ ! -d '/home/ubuntu/env' ]
then 
	python -m virtualenv /home/ubuntu/env
fi

sudo -i -u ubuntu bash << eof
source /home/ubuntu/env/bin/activate
pip install -r /home/ubuntu/everest/ramcov4/lookup/requirements
#nohup python /home/ubuntu/everest/ramcov4/lookup/manage.py runserver 0.0.0.0:5000 &
#eof
